version: '3.9'

services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile.mssql
    ports:
      - "1433:1433"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "80:80"
    environment:
      DB_HOST: mssql
      DB_PORT: 1433
      DB_NAME: mydb
      DB_USER: sa
      DB_PASSWORD: Un!q@to2023
